# Dataset settings
data_root: "../data"

# Model saving
model_path: "../models/saved_model.pth"

# Model architecture
input_size: 784  # 28x28 images flattened
hidden_sizes: [512, 256, 128, 64]  # Two hidden layers
output_size: 10  # Digits 0-9

# Training settings
batch_size: 64
epochs: 20
initial_learning_rate: 0.005
lr_decay_step: 2
lr_decay_gamma: 0.5  # Reduce learning rate by 50% every 10 epochs

# Logging settings
print_every: 5  # Print training info every epoch

# --- Parameters needed for fine-tuning ---
custom_data_folder: "../data/custom_digits" # Path to your saved drawings
finetune_epochs: 20                # Epochs specifically for fine-tuning
finetune_learning_rate: 0.001       # Learning rate for fine-tuning (e.g., 1e-4)
# finetune_batch_size: 32            # Optional: Override batch_size for fine-tuning
# finetune_output_model_suffix: "_finetuned" # Optional: Suffix for the output file